locale                   : "en-US"
title                    : "Siddharth"
title_separator          : "-"
name                     : "Siddharth"
description              : "Computational Materials Science Researcher"
url                      : "https://siddharthb6.github.io"
baseurl                  : ""
repository               : "Siddharthb6/siddharthb6.github.io"
future                   : true
read_more                : "disabled"
words_per_minute         : 160

author:
  name             : "Siddharth"
  avatar           : "/images/profile.jpg"
  bio              : "Computational chemist working on DFT, thermoelectrics, and low-dimensional materials."
  location         : "India"
  email            : "siddharthb610@gmail.com"
  github           : "Siddharthb6"

include:
  - .htaccess
  - _pages

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Kolkata

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

compress_html:
  clippings: all
  ignore:
    envs: development
